services:
  coupon-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-api
    ports:
      - "0.0.0.0:3032:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
